# Generated by Django 5.0.1 on 2024-01-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_productintermediate_product_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productintermediate',
            name='product_name',
        ),
    ]
