# Generated by Django 5.0.1 on 2024-01-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_productintermediate_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productintermediate',
            old_name='Recipe',
            new_name='recipe',
        ),
    ]
