# Generated by Django 5.0.1 on 2024-01-29 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_recipe_productintermediate_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productintermediate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productintermediate',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipe', verbose_name='Рецепт'),
        ),
    ]
